FROM --platform=linux/arm/v7 debian:trixie-slim

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
    ca-certificates \
    wget \
    tar \
    gzip
RUN apt-get install -y openjdk-25-jre-headless

# Set the working directory in the Docker container
WORKDIR /app

# Copy the locally built JAR file into the container
COPY target/*.jar /app/registry-spring-boot-application.jar

# Expose the port your application uses
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/registry-spring-boot-application.jar"]
